# docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    networks:
      - redis-network
    depends_on:
      - redis

  alpr_upload:
    build: ./openalpr-upload
    container_name: alprd-uplaod
    user: root
    volumes:
      - ./static/images:/var/lib/openalpr/plateimages      
      
    
networks:
  redis-network:
    driver: bridge      
volumes:
  redis:
  redis-config:
