# docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    networks:
      - redis-network
    depends_on:
      - redis
  alpr:
    build: ./openalpr-docker
    volumes:
      - ./flask-api/static/images:/var/lib/openalpr/plateimages
    networks:
      - redis-network
  flask-api:
    build: ./flask-api
    ports:
      - 5000:5000
    networks:
      - redis-network
networks:
  redis-network:
    driver: bridge      
volumes:
  redis:
  redis-config:

networks:
  redis-network:
    driver: bridge