listenAddressSingleHTTPFrontend: 0.0.0.0:1337
logLevel: "INFO"
actions:
- title: start redis data base
  icon: restart
  shell: sudo systemctl start alpr-redis.service
  popupOnStart: execution-dialog
    
- title: stop redis data base
  icon: '&#129302;'
  shell: sudo systemctl stop alpr-redis.service
  popupOnStart: execution-dialog


- title: Run data base to csv script
  shell: /home/dell/repos/pyanpr/scripts/exportdb.sh
  shellAfterCompleted: "apprise -t 'Notn:  completed' -b 'completed with code {{ exitCode}}. The log is: \n {{ stdout }} '"
  maxConcurrent: 1
  timeout: 10
  icon: backup
  popupOnStart: execution-dialog

- title: flush redis data base
  icon: ashtonished
  shell: /usr/bin/python3  /home/dell/repos/pyanpr/scripts/flushdb.py
  popupOnStart: execution-dialog

- title: start OpenALPR 
  icon: restart
  shell: sudo systemctl start alpr-openalpr.service 
  popupOnStart: execution-dialog

- title: stop OpenALPR 
  icon: '&#129302;'
  shell: sudo systemctl stop alpr-openalpr.service 
  popupOnStart: execution-dialog

- title: start flask application
  icon: restart
  shell: sudo systemctl start alpr-flask.service
  popupOnStart: execution-dialog

- title: stop flask application 
  icon: '&#129302;'
  shell: sudo systemctl stop alpr-flask.service
  popupOnStart: execution-dialog

- title: start webcam stream
  icon: '&#129302;'
  shell: vlc -vvv v4l2:///dev/video0 --sout '#transcode{vcodec=mp4v,acodec=none}:duplicate{dst=http{mux=ts,dst=:8082/},dst=display}' 
  popupOnStart: execution-dialog


- title: Run service management script
  shell: /home/dell/repos/pyanpr/scripts/mng.sh
  shellAfterCompleted: "apprise -t 'Notn:  completed' -b 'completed with code {{ exitCode}}. The log is: \n {{ stdout }} '"
  maxConcurrent: 1
  timeout: 10
  icon: disk
  popupOnStart: execution-dialog

